#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : zimg
Version  : elease.3.0.5
Release  : 1
URL      : https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.5.tar.gz
Source0  : https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.5.tar.gz
Summary  : Scaling, colorspace conversion, and dithering library
Group    : Development/Tools
License  : MIT WTFPL
Requires: zimg-lib = %{version}-%{release}
Requires: zimg-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
z.lib
======
The "z" library implements the commonly required image processing basics of
scaling, colorspace conversion, and depth conversion. A simple API enables
conversion between any supported formats to operate with minimal knowledge
from the programmer. All library routines were designed from the ground-up
with correctness, flexibility, and thread-safety as first priorities.
Allocation, buffering, and I/O are cleanly separated from processing, allowing
the programmer to adapt "z" to many scenarios.

%package dev
Summary: dev components for the zimg package.
Group: Development
Requires: zimg-lib = %{version}-%{release}
Provides: zimg-devel = %{version}-%{release}
Requires: zimg = %{version}-%{release}

%description dev
dev components for the zimg package.


%package doc
Summary: doc components for the zimg package.
Group: Documentation

%description doc
doc components for the zimg package.


%package lib
Summary: lib components for the zimg package.
Group: Libraries
Requires: zimg-license = %{version}-%{release}

%description lib
lib components for the zimg package.


%package license
Summary: license components for the zimg package.
Group: Default

%description license
license components for the zimg package.


%prep
%setup -q -n zimg-release-3.0.5
cd %{_builddir}/zimg-release-3.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693346897
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1693346897
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zimg
cp %{_builddir}/zimg-release-3.0.5/COPYING %{buildroot}/usr/share/package-licenses/zimg/568dd3613cf8145e8dbb35eeb920bd7d0c662b44 || :
cp %{_builddir}/zimg-release-3.0.5/test/extra/musl-libm/COPYRIGHT %{buildroot}/usr/share/package-licenses/zimg/b134c407093817a6912759192d3a13c09bc7d14b || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/zimg++.hpp
/usr/include/zimg.h
/usr/lib64/libzimg.so
/usr/lib64/pkgconfig/zimg.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/zimg/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzimg.so.2
/usr/lib64/libzimg.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zimg/568dd3613cf8145e8dbb35eeb920bd7d0c662b44
/usr/share/package-licenses/zimg/b134c407093817a6912759192d3a13c09bc7d14b
